- id: commitlint
  name: commitlint
  description: Commitlint hook
  language: node
  entry: commitlint --edit
- id: commitlint-travis
  name: Check commit messages on Travis CI
  description: Lint all relevant commits for a change or PR on Travis CI
  language: node
  entry: commitlint-travis
  always_run: true
  pass_filenames: false
