---
- id: commitlint
  name: Check commit message using commitlint
  description: Lint commit message against @commitlint/config-conventional rules
  language: node
  entry: commitlint
  args: ["--edit"]
  stages: [commit-msg]
- id: commitlint-all
  name: Check ALL commit messages using commitlint
  description: Lint ALL commit messages against @commitlint/config-conventional rules
  language: node
  entry: commitlint
  args: ["--from", "--"]
  stages: [manual]
