name: Release version

on:
  push:
    branches:
      - 'master'

jobs:
  bump-version:
    name: 'Release a new version'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create new release
        if: steps.semantic.outputs.new_release_published == 'true'
        run: gh release create ${{ steps.semantic.outputs.new_release_git_tag }}